import { loadPluginManifestRegistry } from "../plugins/manifest-registry.js";
import { loadBundledChannelSecretContractApi } from "./channel-contract-api.js";
import type { SecretTargetRegistryEntry } from "./target-registry-types.js";

const SECRET_INPUT_SHAPE = "secret_input"; // Pragma: allowlist secret
const SIBLING_REF_SHAPE = "sibling_ref"; // Pragma: allowlist secret

function listChannelSecretTargetRegistryEntries(): SecretTargetRegistryEntry[] {
  const entries: SecretTargetRegistryEntry[] = [];

  for (const record of loadPluginManifestRegistry({}).plugins) {
    if (record.origin !== "bundled") {
      continue;
    }
    const channelIds = record.channels;
    if (channelIds.length === 0) {
      continue;
    }
    try {
      const contractApi = loadBundledChannelSecretContractApi(record.id);
      entries.push(...(contractApi?.secretTargetRegistryEntries ?? []));
    } catch {
      // Ignore bundled channels that do not expose a usable secret contract artifact.
    }
  }
  return entries;
}

const CORE_SECRET_TARGET_REGISTRY: SecretTargetRegistryEntry[] = [
  {
    authProfileType: "api_key",
    configFile: "auth-profiles.json",
    expectedResolvedValue: "string",
    id: "auth-profiles.api_key.key",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "profiles.*.key",
    refPathPattern: "profiles.*.keyRef",
    secretShape: SIBLING_REF_SHAPE,
    targetType: "auth-profiles.api_key.key",
  },
  {
    authProfileType: "token",
    configFile: "auth-profiles.json",
    expectedResolvedValue: "string",
    id: "auth-profiles.token.token",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "profiles.*.token",
    refPathPattern: "profiles.*.tokenRef",
    secretShape: SIBLING_REF_SHAPE,
    targetType: "auth-profiles.token.token",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "agents.defaults.memorySearch.remote.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "agents.defaults.memorySearch.remote.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "agents.defaults.memorySearch.remote.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "agents.list[].memorySearch.remote.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "agents.list[].memorySearch.remote.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "agents.list[].memorySearch.remote.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "cron.webhookToken",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "cron.webhookToken",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "cron.webhookToken",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "gateway.auth.token",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "gateway.auth.token",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "gateway.auth.token",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "gateway.auth.password",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "gateway.auth.password",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "gateway.auth.password",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "gateway.remote.password",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "gateway.remote.password",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "gateway.remote.password",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "gateway.remote.token",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "gateway.remote.token",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "gateway.remote.token",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "messages.tts.providers.*.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "messages.tts.providers.*.apiKey",
    providerIdPathSegmentIndex: 3,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "messages.tts.providers.*.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.apiKey",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.apiKey",
    targetTypeAliases: ["models.providers.*.apiKey"],
    trackProviderShadowing: true,
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.headers.*",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.headers.*",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.headers",
    targetTypeAliases: ["models.providers.*.headers.*"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.headers.*",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.headers.*",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.headers",
    targetTypeAliases: ["models.providers.*.request.headers.*"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.auth.token",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.auth.token",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.auth.token",
    targetTypeAliases: ["models.providers.*.request.auth.token"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.auth.value",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.auth.value",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.auth.value",
    targetTypeAliases: ["models.providers.*.request.auth.value"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.proxy.tls.ca",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.proxy.tls.ca",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.proxy.tls.ca",
    targetTypeAliases: ["models.providers.*.request.proxy.tls.ca"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.proxy.tls.cert",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.proxy.tls.cert",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.proxy.tls.cert",
    targetTypeAliases: ["models.providers.*.request.proxy.tls.cert"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.proxy.tls.key",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.proxy.tls.key",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.proxy.tls.key",
    targetTypeAliases: ["models.providers.*.request.proxy.tls.key"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.proxy.tls.passphrase",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.proxy.tls.passphrase",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.proxy.tls.passphrase",
    targetTypeAliases: ["models.providers.*.request.proxy.tls.passphrase"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.tls.ca",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.tls.ca",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.tls.ca",
    targetTypeAliases: ["models.providers.*.request.tls.ca"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.tls.cert",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.tls.cert",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.tls.cert",
    targetTypeAliases: ["models.providers.*.request.tls.cert"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.tls.key",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.tls.key",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.tls.key",
    targetTypeAliases: ["models.providers.*.request.tls.key"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "models.providers.*.request.tls.passphrase",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "models.providers.*.request.tls.passphrase",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "models.providers.request.tls.passphrase",
    targetTypeAliases: ["models.providers.*.request.tls.passphrase"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "skills.entries.*.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "skills.entries.*.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "skills.entries.apiKey",
    targetTypeAliases: ["skills.entries.*.apiKey"],
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "talk.providers.*.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "talk.providers.*.apiKey",
    providerIdPathSegmentIndex: 2,
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "talk.providers.*.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "tools.web.search.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "tools.web.search.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "tools.web.search.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.brave.config.webSearch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.brave.config.webSearch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.brave.config.webSearch.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.google.config.webSearch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.google.config.webSearch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.google.config.webSearch.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.xai.config.webSearch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.xai.config.webSearch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.xai.config.webSearch.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.moonshot.config.webSearch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.moonshot.config.webSearch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.moonshot.config.webSearch.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.perplexity.config.webSearch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.perplexity.config.webSearch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.perplexity.config.webSearch.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.firecrawl.config.webSearch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.firecrawl.config.webSearch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.firecrawl.config.webSearch.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.firecrawl.config.webFetch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.firecrawl.config.webFetch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.firecrawl.config.webFetch.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.tavily.config.webSearch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.tavily.config.webSearch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.tavily.config.webSearch.apiKey",
  },
  {
    configFile: "openclaw.json",
    expectedResolvedValue: "string",
    id: "plugins.entries.minimax.config.webSearch.apiKey",
    includeInAudit: true,
    includeInConfigure: true,
    includeInPlan: true,
    pathPattern: "plugins.entries.minimax.config.webSearch.apiKey",
    secretShape: SECRET_INPUT_SHAPE,
    targetType: "plugins.entries.minimax.config.webSearch.apiKey",
  },
];

let cachedSecretTargetRegistry: SecretTargetRegistryEntry[] | null = null;

export function getCoreSecretTargetRegistry(): SecretTargetRegistryEntry[] {
  return CORE_SECRET_TARGET_REGISTRY;
}

export function getSecretTargetRegistry(): SecretTargetRegistryEntry[] {
  if (cachedSecretTargetRegistry) {
    return cachedSecretTargetRegistry;
  }
  cachedSecretTargetRegistry = [
    ...CORE_SECRET_TARGET_REGISTRY,
    ...listChannelSecretTargetRegistryEntries(),
  ];
  return cachedSecretTargetRegistry;
}
